[theme]
primaryColor = "#004225"           # British Racing Green
backgroundColor = "#e3e3e3"        # Light grey background
secondaryBackgroundColor = "#f8f8f8"
textColor = "#111111"
font = "sans serif"
